# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "ON")
set(CPACK_BINARY_NUGET "OFF")
set(CPACK_BINARY_WIX "OFF")
set(CPACK_BINARY_ZIP "OFF")
set(CPACK_BUILD_SOURCE_DIRS "/project/armgcc;/project/armgcc")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.22/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "threadx_demo built using CMake")
set(CPACK_GENERATOR "ZIP")
set(CPACK_IGNORE_FILES "\\.git/;\\.github/;_build/;\\.git;\\.gitattributes;\\.gitignore;.*~\$")
set(CPACK_INSTALLED_DIRECTORIES "/project/armgcc;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/project/sdk/devices/MIMXRT1062/.;/project/sdk/devices/MIMXRT1062/../../CMSIS/Core/Include;/project/sdk/devices/MIMXRT1062/../../CMSIS/DSP;/project/sdk/devices/MIMXRT1062/../../CMSIS/Driver;/project/sdk/devices/MIMXRT1062/../../CMSIS/NN;/project/sdk/devices/MIMXRT1062/../../CMSIS/RTOS2;/project/sdk/devices/MIMXRT1062/../../CMSIS/RTOS2/Include;/project/sdk/devices/MIMXRT1062/../../boards/evkbmimxrt1060/crank_storyboard_examples/template;/project/sdk/devices/MIMXRT1062/../../boards/evkbmimxrt1060/project_template;/project/sdk/devices/MIMXRT1062/../../boards/evkbmimxrt1060/wireless_config_template;/project/sdk/devices/MIMXRT1062/../../boards/evkbmimxrt1060/xip;/project/sdk/devices/MIMXRT1062/../../boards/evkbmimxrt1060_om13790host/project_template;/project/sdk/devices/MIMXRT1062/../../boards/evkcmimxrt1060/crank_storyboard_examples/template;/project/sdk/devices/MIMXRT1062/../../boards/evkcmimxrt1060/edgefast_bluetooth_examples/template;/project/sdk/devices/MIMXRT1062/../../boards/evkcmimxrt1060/project_template;/project/sdk/devices/MIMXRT1062/../../boards/evkcmimxrt1060/wireless_config_template;/project/sdk/devices/MIMXRT1062/../../boards/evkcmimxrt1060/xip;/project/sdk/devices/MIMXRT1062/../../boards/evkmimxrt1060/crank_storyboard_examples/template;/project/sdk/devices/MIMXRT1062/../../boards/evkmimxrt1060/project_template;/project/sdk/devices/MIMXRT1062/../../boards/evkmimxrt1060/wireless_config_template;/project/sdk/devices/MIMXRT1062/../../boards/evkmimxrt1060/xip;/project/sdk/devices/MIMXRT1062/../../boards/evkmimxrt1060_om13790host/project_template;/project/sdk/devices/MIMXRT1062/../../components/audio;/project/sdk/devices/MIMXRT1062/../../components/button;/project/sdk/devices/MIMXRT1062/../../components/codec;/project/sdk/devices/MIMXRT1062/../../components/codec/cs42448;/project/sdk/devices/MIMXRT1062/../../components/codec/cs42888;/project/sdk/devices/MIMXRT1062/../../components/codec/da7212;/project/sdk/devices/MIMXRT1062/../../components/codec/i2c;/project/sdk/devices/MIMXRT1062/../../components/codec/sgtl5000;/project/sdk/devices/MIMXRT1062/../../components/codec/wm8904;/project/sdk/devices/MIMXRT1062/../../components/codec/wm8960;/project/sdk/devices/MIMXRT1062/../../components/codec/wm8962;/project/sdk/devices/MIMXRT1062/../../components/common_task;/project/sdk/devices/MIMXRT1062/../../components/crc;/project/sdk/devices/MIMXRT1062/../../components/edgefast_wifi;/project/sdk/devices/MIMXRT1062/../../components/exception_handling;/project/sdk/devices/MIMXRT1062/../../components/flash/mflash;/project/sdk/devices/MIMXRT1062/../../components/flash/mflash/evkcmimxrt1060;/project/sdk/devices/MIMXRT1062/../../components/flash/mflash/mimxrt1062;/project/sdk/devices/MIMXRT1062/../../components/flash/nand;/project/sdk/devices/MIMXRT1062/../../components/flash/nand/flexspi;/project/sdk/devices/MIMXRT1062/../../components/flash/nand/semc;/project/sdk/devices/MIMXRT1062/../../components/flash/nor;/project/sdk/devices/MIMXRT1062/../../components/flash/nor/flexspi;/project/sdk/devices/MIMXRT1062/../../components/flash/nor/lpspi;/project/sdk/devices/MIMXRT1062/../../components/ft5406;/project/sdk/devices/MIMXRT1062/../../components/ft5406_rt;/project/sdk/devices/MIMXRT1062/../../components/ft6x06;/project/sdk/devices/MIMXRT1062/../../components/fxls8974cf;/project/sdk/devices/MIMXRT1062/../../components/fxos8700cq;/project/sdk/devices/MIMXRT1062/../../components/gpio;/project/sdk/devices/MIMXRT1062/../../components/gt911;/project/sdk/devices/MIMXRT1062/../../components/i2c;/project/sdk/devices/MIMXRT1062/../../components/ili9341;/project/sdk/devices/MIMXRT1062/../../components/internal_flash;/project/sdk/devices/MIMXRT1062/../../components/led;/project/sdk/devices/MIMXRT1062/../../components/lists;/project/sdk/devices/MIMXRT1062/../../components/log;/project/sdk/devices/MIMXRT1062/../../components/mem_manager;/project/sdk/devices/MIMXRT1062/../../components/messaging;/project/sdk/devices/MIMXRT1062/../../components/mma8451q;/project/sdk/devices/MIMXRT1062/../../components/mx25r_flash;/project/sdk/devices/MIMXRT1062/../../components/nvm;/project/sdk/devices/MIMXRT1062/../../components/osa;/project/sdk/devices/MIMXRT1062/../../components/panic;/project/sdk/devices/MIMXRT1062/../../components/pf1550;/project/sdk/devices/MIMXRT1062/../../components/pf3000;/project/sdk/devices/MIMXRT1062/../../components/phy;/project/sdk/devices/MIMXRT1062/../../components/phy/device/phyksz8081;/project/sdk/devices/MIMXRT1062/../../components/reset;/project/sdk/devices/MIMXRT1062/../../components/rng;/project/sdk/devices/MIMXRT1062/../../components/rtt;/project/sdk/devices/MIMXRT1062/../../components/serial_manager;/project/sdk/devices/MIMXRT1062/../../components/silicon_id;/project/sdk/devices/MIMXRT1062/../../components/silicon_id/socs/rt10xx;/project/sdk/devices/MIMXRT1062/../../components/spi;/project/sdk/devices/MIMXRT1062/../../components/time_stamp;/project/sdk/devices/MIMXRT1062/../../components/timer;/project/sdk/devices/MIMXRT1062/../../components/timer_manager;/project/sdk/devices/MIMXRT1062/../../components/uart;/project/sdk/devices/MIMXRT1062/../../components/video;/project/sdk/devices/MIMXRT1062/../../components/video/camera;/project/sdk/devices/MIMXRT1062/../../components/video/camera/device;/project/sdk/devices/MIMXRT1062/../../components/video/camera/device/mt9m114;/project/sdk/devices/MIMXRT1062/../../components/video/camera/device/ov7725;/project/sdk/devices/MIMXRT1062/../../components/video/camera/device/sccb;/project/sdk/devices/MIMXRT1062/../../components/video/camera/receiver;/project/sdk/devices/MIMXRT1062/../../components/video/camera/receiver/csi;/project/sdk/devices/MIMXRT1062/../../components/video/display;/project/sdk/devices/MIMXRT1062/../../components/video/display/dc;/project/sdk/devices/MIMXRT1062/../../components/video/display/dc/elcdif;/project/sdk/devices/MIMXRT1062/../../components/video/display/fbdev;/project/sdk/devices/MIMXRT1062/../../components/video/i2c;/project/sdk/devices/MIMXRT1062/../../components/wifi_bt_module;/project/sdk/devices/MIMXRT1062/../../components/wifi_bt_module/template;/project/sdk/devices/MIMXRT1062/../../middleware/Crank_Software;/project/sdk/devices/MIMXRT1062/../../middleware/EmbeddedWizard;/project/sdk/devices/MIMXRT1062/../../middleware/arm-pelion;/project/sdk/devices/MIMXRT1062/../../middleware/aws_iot/device-defender;/project/sdk/devices/MIMXRT1062/../../middleware/aws_iot/device-shadow;/project/sdk/devices/MIMXRT1062/../../middleware/aws_iot/iot-reference;/project/sdk/devices/MIMXRT1062/../../middleware/aws_iot/iot-reference/Middleware/FreeRTOS/mqtt-agent-interface;/project/sdk/devices/MIMXRT1062/../../middleware/aws_iot/iot-reference/Middleware/FreeRTOS/transport_mbedtls;/project/sdk/devices/MIMXRT1062/../../middleware/aws_iot/iot-reference/Middleware/NXP/pkcs11;/project/sdk/devices/MIMXRT1062/../../middleware/aws_iot/iot-reference/examples/common/cli;/project/sdk/devices/MIMXRT1062/../../middleware/aws_iot/iot-reference/examples/common/kvstore;/project/sdk/devices/MIMXRT1062/../../middleware/aws_iot/iot-reference/examples/common/logging;/project/sdk/devices/MIMXRT1062/../../middleware/aws_iot/iot-reference/examples/common/mqtt_agent;/project/sdk/devices/MIMXRT1062/../../middleware/aws_iot/iot-reference/examples/common/ota;/project/sdk/devices/MIMXRT1062/../../middleware/aws_iot/iot-reference/examples/evkbmimxrt1060/shadow;/project/sdk/devices/MIMXRT1062/../../middleware/aws_iot/jobs;/project/sdk/devices/MIMXRT1062/../../middleware/aws_iot/ota;/project/sdk/devices/MIMXRT1062/../../middleware/bm;/project/sdk/devices/MIMXRT1062/../../middleware/canopen;/project/sdk/devices/MIMXRT1062/../../middleware/canopen/mco;/project/sdk/devices/MIMXRT1062/../../middleware/dhara;/project/sdk/devices/MIMXRT1062/../../middleware/edgefast_bluetooth;/project/sdk/devices/MIMXRT1062/../../middleware/edgefast_bluetooth/lib;/project/sdk/devices/MIMXRT1062/../../middleware/eiq;/project/sdk/devices/MIMXRT1062/../../middleware/eiq/tensorflow-lite;/project/sdk/devices/MIMXRT1062/../../middleware/eiq/tensorflow-lite/third_party/cmsis_nn;/project/sdk/devices/MIMXRT1062/../../middleware/eiq/tensorflow-lite/third_party/kissfft;/project/sdk/devices/MIMXRT1062/../../middleware/eiq/tensorflow-lite/third_party/xa_nnlib_hifi4;/project/sdk/devices/MIMXRT1062/../../middleware/emwin;/project/sdk/devices/MIMXRT1062/../../middleware/fatfs;/project/sdk/devices/MIMXRT1062/../../middleware/freemaster;/project/sdk/devices/MIMXRT1062/../../middleware/issdk;/project/sdk/devices/MIMXRT1062/../../middleware/libjpeg;/project/sdk/devices/MIMXRT1062/../../middleware/littlefs;/project/sdk/devices/MIMXRT1062/../../middleware/llhttp;/project/sdk/devices/MIMXRT1062/../../middleware/lvgl;/project/sdk/devices/MIMXRT1062/../../middleware/lvgl/lvgl_sdk;/project/sdk/devices/MIMXRT1062/../../middleware/lwip;/project/sdk/devices/MIMXRT1062/../../middleware/maestro;/project/sdk/devices/MIMXRT1062/../../middleware/maestro/mcu-audio/asrc;/project/sdk/devices/MIMXRT1062/../../middleware/maestro/mcu-audio/ogg;/project/sdk/devices/MIMXRT1062/../../middleware/maestro/mcu-audio/opus;/project/sdk/devices/MIMXRT1062/../../middleware/maestro/mcu-audio/opusfile;/project/sdk/devices/MIMXRT1062/../../middleware/mbedtls;/project/sdk/devices/MIMXRT1062/../../middleware/mcu_bootloader;/project/sdk/devices/MIMXRT1062/../../middleware/mcuboot_opensource;/project/sdk/devices/MIMXRT1062/../../middleware/mcuboot_opensource/boot/bootutil;/project/sdk/devices/MIMXRT1062/../../middleware/motor_control;/project/sdk/devices/MIMXRT1062/../../middleware/multicore;/project/sdk/devices/MIMXRT1062/../../middleware/openh264;/project/sdk/devices/MIMXRT1062/../../middleware/pkcs11;/project/sdk/devices/MIMXRT1062/../../middleware/pngdec;/project/sdk/devices/MIMXRT1062/../../middleware/rtcesl;/project/sdk/devices/MIMXRT1062/../../middleware/sdmmc;/project/sdk/devices/MIMXRT1062/../../middleware/se_hostlib;/project/sdk/devices/MIMXRT1062/../../middleware/soem;/project/sdk/devices/MIMXRT1062/../../middleware/tinycbor;/project/sdk/devices/MIMXRT1062/../../middleware/usb;/project/sdk/devices/MIMXRT1062/../../middleware/vit;/project/sdk/devices/MIMXRT1062/../../middleware/voice_seeker/ARM_CortexM7;/project/sdk/devices/MIMXRT1062/../../middleware/voice_seeker/ARM_CortexM7/rdsp_utilities_public;/project/sdk/devices/MIMXRT1062/../../middleware/wifi_nxp;/project/sdk/devices/MIMXRT1062/../../middleware/wireless;/project/sdk/devices/MIMXRT1062/../../middleware/wireless/ethermind;/project/sdk/devices/MIMXRT1062/../../middleware/wireless/framework;/project/sdk/devices/MIMXRT1062/../../middleware/wireless/wpa_supplicant-rtos;/project/sdk/devices/MIMXRT1062/../../rtos/azure-rtos;/project/sdk/devices/MIMXRT1062/../../rtos/freertos/backoffalgorithm;/project/sdk/devices/MIMXRT1062/../../rtos/freertos/corehttp;/project/sdk/devices/MIMXRT1062/../../rtos/freertos/corejson;/project/sdk/devices/MIMXRT1062/../../rtos/freertos/coremqtt;/project/sdk/devices/MIMXRT1062/../../rtos/freertos/coremqtt-agent;/project/sdk/devices/MIMXRT1062/../../rtos/freertos/corepkcs11;/project/sdk/devices/MIMXRT1062/../../rtos/freertos/freertos-kernel;/project/sdk/devices/MIMXRT1062/../../rtos/freertos/freertos-plus-tcp;/project/sdk/devices/MIMXRT1062/cmsis_drivers;/project/sdk/devices/MIMXRT1062/drivers;/project/sdk/devices/MIMXRT1062/project_template;/project/sdk/devices/MIMXRT1062/template;/project/sdk/devices/MIMXRT1062/utilities;/project/sdk/devices/MIMXRT1062/utilities/debug_console_lite;/project/sdk/devices/MIMXRT1062/utilities/shell;/project/sdk/devices/MIMXRT1062/xip")
set(CPACK_NSIS_DISPLAY_NAME "threadx_demo 0.1.1")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "\$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "threadx_demo 0.1.1")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "/project/armgcc/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.22/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "threadx_demo built using CMake")
set(CPACK_PACKAGE_FILE_NAME "threadx_demo-0.1.1-Source")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "threadx_demo 0.1.1")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "threadx_demo 0.1.1")
set(CPACK_PACKAGE_NAME "threadx_demo")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Humanity")
set(CPACK_PACKAGE_VERSION "0.1.1")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_RESOURCE_FILE_LICENSE "/usr/share/cmake-3.22/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake-3.22/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.22/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "ZIP")
set(CPACK_SOURCE_IGNORE_FILES "\\.git/;\\.github/;_build/;\\.git;\\.gitattributes;\\.gitignore;.*~\$")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/project/armgcc;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/project/armgcc/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "threadx_demo-0.1.1-Source")
set(CPACK_SOURCE_TOPLEVEL_TAG "Generic-Source")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Generic")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Generic-Source")
set(CPACK_VERBATIM_VARIABLES "YES")
set(CPACK_WIX_SIZEOF_VOID_P "")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/project/armgcc/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
